# LIST - IN OPERATOR 
'''

    LIST N OPERATOR 
    OPERATOR IN MENGEMBALIKAN TRUE ATAU FALSE. 
    SETELAH MEMERIKSA UNTUK MELIHAT APAKAH SUATA ELEMENT BERADA PADA SEBUHAN LIST TERTENTU, JIKA DITEMUKN, IA MENGEMBALIKAN TRUE DAN FALSE JIKA TIDAK.
    (OPERATOR not in MENGHASILKAN KEBALIKAN NYA)  SEHINGGA OPERATOR INI COCOK UNTUK MEMVALIDASI APAKAJ DATA YANG KITA INGINKAN ADA DIDALAM LIST TERSEBUT . 

    CONTOH PENERAPAN OPERATOR in BISA DI LIHAT PADA KODE DI BAWAH INI

'''

a_list = [10, 20, 30, 40]
10 in a_list
# TRUE



50 list a_list
# FALSE

10 not in a_list
# FALSE 

50 not in a_list
# TRUE


for n in a_list:    
    print(n, end=' ')

