"""

VARIABLE ASSIGNMENT 

Variabel assignmenet dalam python adalah proses memberikan nama atau label pada nilai yang telah di hitung atau di hasilkan oleh program, sehingga nilai tersebut dapat digunakan kembali didalam program dengan memanggil nama variabel tersrbut : 



Contoh sederhana : 
"""

x = 10



"""
    PADA CONTOH DIATAS, 'x' ADALAH VARIABEL YANG DIBERI NILAI '10' DENGAN BEGITU NILAI '10' DAPAT DIGUNAKAN KEMBALI DIDALAM PROGRAM DENGAN MEMANGGIL VARIABEL 'X'. 


    VAIRABEL DI PYTHON TIDAK MEMERLUKAN DEKLARASI TIPE DATA YANG KHUSUS, KARENA TIPE DATA DARI VARIABLE AKAN SECARA OTOMATIS DISESUAIKAN DENGAN NILAI YANG DIISIKAN PADA VARIABEL TERSEBUT . 

    OLEH KARENA ITU, PYTHON DIKATEGORIKAN SEBAGAI BAHASA PEMOGRAMAN YANG BERSIFAT DYNAMICALLY-TYPED 


    
    CONTOH : 
    LIHATLAH UNGKAPAN INI ;RESULT = '100 + 200'
    EKPRESI INI BERARTI BAHWA KITA MENETAPKAN NILAI DISEBALAH KANAN KE VARIABEL SEBELAH KIRI 



    TANDA '=' PADA KODE 'HASIL' = 100 + 200' 
    EKPRESI INI BERARTI BAHWA KITA MENETAPKAN NILAI DI SEBELAH KANAN . 
    operator = dalamvariabelhsildisebealahkiri =. 
    Operator = '=' disebut operator assignmenet operator . 



"""


# PYTHON SIMULTANEOUS ASSIGNMENET 
# SEPERTI YANG DITUJUKKAN DALAM EKPRESI X,Y = 100,200, DIMUNGKINKAN UNTUK MENETAPKAN BEBERAPA VARIABEL KE NILAI DALAM SATU BARIS SECARA BERSAMAAN . INI DISEBUT SIMULTANEOUS ASSIGNMENT . 
x,y     = 100,200
result = x + y 
print(result)


# outoput :  300 





# PYTHON MULTIPLE ASSIGNMNET 
# SEPERTI YANG DI TUJUKKAN PADA num1 = numb2 = num3 = 200, ANDA DAPAT MENETAPKAN NILAI 200 KE BEBERAPA VARIABEL SEKALIGUS : 

num1 = num2 = num3 = 200 
print(num1,num2,num3)

# output : 200 200 200 